/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADialog: typeof import('@arco-design/web-vue')['Dialog']
    CheckAppVersion: typeof import('./src/components/CheckAppVersion.vue')['default']
    Had: typeof import('./src/components/had.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snoke: typeof import('./src/components/Snoke.vue')['default']
    Snowflake: typeof import('./src/components/Snowflake.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
